# Generated by Django 2.1.3 on 2018-12-15 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('advStartDate', models.DateField()),
                ('advEndDate', models.DateField()),
                ('advDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Read', 'Read'), ('Write', 'Write'), ('Delete', 'Delete'), ('Update', 'Update')], default='Read', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyID', models.IntegerField()),
                ('propertyTitle', models.CharField(max_length=100)),
                ('propertyStreet', models.CharField(max_length=200)),
                ('propertyPostalCode', models.CharField(max_length=200)),
                ('propertyStreetNumber', models.CharField(max_length=200)),
                ('propertyConstructionDate', models.DateField()),
                ('propertyRegistrationDate', models.DateField()),
                ('propertyNoOfHalls', models.IntegerField()),
                ('propertyNoOfBedRooms', models.IntegerField()),
                ('propertyNoOfBathRooms', models.FloatField()),
                ('propertyNoOfFloors', models.IntegerField()),
                ('propertyTotalArea', models.FloatField()),
                ('propertyAskingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('propertySellingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyCategoryName', models.CharField(choices=[('Single House', 'Single House'), ('Attached House', 'Attached House'), ('Town House', 'Town House'), ('Apartment', 'Apartment'), ('Store', 'Store'), ('Farm', 'Farm'), ('Factory', 'Factory'), ('Mall', 'Mall'), ('Building', 'Building'), ('Other', 'Other')], default='Single House', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFacing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyFacingName', models.CharField(choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West'), ('Other', 'Other')], default='North', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('propertyImageID', models.AutoField(primary_key=True, serialize=False)),
                ('propertyImage', models.ImageField(blank=True, default='', upload_to='')),
                ('propertyImageDescription', models.CharField(max_length=500)),
                ('propertyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertySector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertySectorName', models.CharField(choices=[('Private', 'Private'), ('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Government', 'Government'), ('Rural', 'Rural'), ('Other', 'Other')], default='Private', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinceName', models.CharField(max_length=100)),
                ('countryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Country')),
            ],
        ),
        migrations.CreateModel(
            name='RoleCode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SysFeature',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SysFeatureRole',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(default='admin_portal', max_length=100)),
                ('featurename', models.CharField(default='add user', max_length=100)),
                ('permissiontype', models.CharField(default='read', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='abc', max_length=100)),
                ('rolename', models.CharField(default='admin_portal', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.PropertyCategory'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.City'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Country'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_facing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.PropertyFacing'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Province'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.PropertySector'),
        ),
        migrations.AddField(
            model_name='city',
            name='countryName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='provinceName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eproperty.Province'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advProperty',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eproperty.Property'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
